/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { HeroSnippet, BriefTask, RoomRow, PeopleContact, DrawerDetail, SearchPrompt } from './types';

export const HERO_SNIPPETS: HeroSnippet[] = [
  {
    id: 's1',
    type: 'employment',
    title: 'IPF OS PLATFORM',
    meta: 'Enterprise system • Web + mobile',
    body: 'Cross-platform operations product covering PMO, tasks, meals, and user management.',
    color: '#fffdf4',
    stamp: 'FLAGSHIP',
    stampColor: '#386dbd',
    left: '8%',
    top: '12%',
    width: '190px',
    rotation: -10,
    delay: 0.1,
  },
  {
    id: 's2',
    type: 'note',
    title: 'ROLE STACK',
    meta: 'Full stack • DevOps • Mobile',
    body: 'Shipping product across Flutter, React, TypeScript, Firebase, and backend systems.',
    color: '#fcfcfc',
    badge: 'PROFILE',
    left: '24%',
    top: '8%',
    width: '210px',
    rotation: 6,
    delay: 0.16,
  },
  {
    id: 's3',
    type: 'promo',
    title: 'BANTU SOKO',
    meta: 'Play Store release',
    body: 'Marketplace and service aggregation app built to reduce app fatigue for users.',
    color: '#f8fcff',
    stamp: 'PUBLISHED',
    stampColor: '#378b60',
    left: '74%',
    top: '10%',
    width: '185px',
    rotation: -8,
    delay: 0.22,
  },
  {
    id: 's4',
    type: 'note',
    title: 'SOLOMON STOCKBROKER',
    meta: 'Mobile investing experience',
    body: 'Stock trading flows, portfolio tracking, and real-time market information.',
    color: '#fff8f1',
    badge: 'FINTECH',
    left: '86%',
    top: '18%',
    width: '180px',
    rotation: 12,
    delay: 0.28,
  },
  {
    id: 's5',
    type: 'note',
    title: 'CHANGISHA APP',
    meta: 'Crowdfunding platform',
    body: 'Built for campaign creation, contribution flow, and mobile-money-friendly fundraising.',
    color: '#faf6f0',
    left: '6%',
    top: '38%',
    width: '185px',
    rotation: 9,
    delay: 0.34,
  },
  {
    id: 's6',
    type: 'note',
    title: 'MEALGRO',
    meta: 'Meal planning mobile product',
    body: 'Feeds, filters, shopping flows, and practical UX around reducing food waste.',
    color: '#eefcf5',
    badge: 'HEALTH',
    left: '12%',
    top: '66%',
    width: '190px',
    rotation: -7,
    delay: 0.4,
  },
  {
    id: 's7',
    type: 'note',
    title: 'TUMAFAST',
    meta: 'Delivery app',
    body: 'Local logistics product with location-aware delivery tracking and pickup flow.',
    color: '#faf9f5',
    left: '26%',
    top: '82%',
    width: '170px',
    rotation: -11,
    delay: 0.46,
  },
  {
    id: 's8',
    type: 'note',
    title: 'IMBEJU CRDB',
    meta: 'Offline-first finance tooling',
    body: 'Group savings workflows for VIKOBA communities with local-first records.',
    color: '#ffffff',
    stamp: 'OFFLINE',
    stampColor: '#cc4539',
    left: '42%',
    top: '84%',
    width: '210px',
    rotation: 4,
    delay: 0.52,
  },
  {
    id: 's9',
    type: 'note',
    title: 'OCEAN E-COMMERCE',
    meta: 'Manufacturer to customer flow',
    body: 'An e-commerce system focused on simplifying distribution and direct reach.',
    color: '#fffdf5',
    badge: 'COMMERCE',
    left: '72%',
    top: '80%',
    width: '180px',
    rotation: -14,
    delay: 0.58,
  },
  {
    id: 's10',
    type: 'note',
    title: 'CYPHERZ',
    meta: 'Agriculture platform',
    body: 'Marketplace concept linking sellers and buyers directly without the middle layer.',
    color: '#fffcf0',
    left: '88%',
    top: '72%',
    width: '155px',
    rotation: 10,
    delay: 0.64,
  },
  {
    id: 's11',
    type: 'note',
    title: 'VIKOBA+',
    meta: 'Small-group money management',
    body: 'Expense and income tracking designed for community finance groups.',
    color: '#faf9f5',
    left: '84%',
    top: '42%',
    width: '145px',
    rotation: -6,
    delay: 0.7,
  },
  {
    id: 's12',
    type: 'note',
    title: 'CODE CHALLENGE APP',
    meta: 'Trello-style planning',
    body: 'Boards, lists, and collaboration patterns for structured task execution.',
    color: '#fffff8',
    stamp: 'WEB APP',
    stampColor: '#386dbd',
    left: '68%',
    top: '49%',
    width: '185px',
    rotation: 7,
    delay: 0.76,
  },
  {
    id: 's13',
    type: 'note',
    title: 'CAREER NOTE',
    meta: 'IPF Software • 2025-present',
    body: 'Mobile engineer shipping real product flows and collaborating closely with UI and backend teams.',
    color: '#fffdf0',
    left: '46%',
    top: '4%',
    width: '150px',
    rotation: -4,
    delay: 0.82,
  },
  {
    id: 's14',
    type: 'note',
    title: 'CAREER NOTE',
    meta: 'Freelancing • 2023-present',
    body: 'Cross-platform mobile delivery, QA support, reviews, and product cleanup work.',
    color: '#ffffff',
    badge: 'FREELANCE',
    left: '58%',
    top: '6%',
    width: '140px',
    rotation: 10,
    delay: 0.88,
  },
  {
    id: 's15',
    type: 'note',
    title: 'CAREER NOTE',
    meta: 'Trilabs Limited',
    body: 'Backend and DevOps work around transport booking, payments, APIs, and delivery pipelines.',
    color: '#fcfcf0',
    left: '3%',
    top: '25%',
    width: '155px',
    rotation: -17,
    delay: 0.94,
  },
  {
    id: 's16',
    type: 'note',
    title: 'STACK CARD',
    meta: 'Flutter • React • TypeScript',
    body: 'Also shipping with Firebase, Node.js, REST APIs, PostgreSQL, SQLite, and CI/CD habits.',
    color: '#eef8ff',
    left: '27%',
    top: '28%',
    width: '160px',
    rotation: 5,
    delay: 1.0,
  },
  {
    id: 's17',
    type: 'note',
    title: 'EXPERIMENT',
    meta: 'Tetris Game',
    body: 'A lightweight mobile game project focused on controls, polish, and repeatable gameplay feel.',
    color: '#fcfcfc',
    stamp: 'FUN BUILD',
    stampColor: '#378b60',
    left: '79%',
    top: '31%',
    width: '150px',
    rotation: -8,
    delay: 1.06,
  },
  {
    id: 's18',
    type: 'note',
    title: 'FOCUS',
    meta: 'Scalable apps, practical UX',
    body: 'A portfolio centered on products that solve day-to-day operational and consumer problems.',
    color: '#fffbf4',
    left: '62%',
    top: '20%',
    width: '180px',
    rotation: 2,
    delay: 1.12,
  },
];

export const BRIEF_TASKS: BriefTask[] = [
  {
    id: 'b1',
    category: 'MUST SEE',
    title: 'Turn IPF OS into a polished case study with web and mobile screenshots',
    sender: 'Portfolio Desk',
    time: 'Today',
    tags: ['Case Study', 'Flagship'],
    snippet: 'The enterprise platform is the strongest proof of system thinking. Lead with the product story, architecture, and impact.',
    actionRequired: true,
  },
  {
    id: 'b2',
    category: 'MUST SEE',
    title: 'Refine portfolio storytelling around full stack, DevOps, and mobile engineering',
    sender: 'Profile Review',
    time: 'This week',
    tags: ['Positioning'],
    snippet: 'Your strongest signal is breadth with shipping experience: Flutter, React, backend integration, and product delivery.',
  },
  {
    id: 'b3',
    category: 'FYI',
    title: 'Bantu Soko and Ocean releases already provide public product proof',
    sender: 'Product Index',
    time: 'Pinned',
    tags: ['Published Work'],
    snippet: 'Keep live links visible so visitors can validate that these are real shipped products.',
  },
  {
    id: 'b4',
    category: 'FYI',
    title: 'Freelance and startup work show a useful mix of delivery speed and ownership',
    sender: 'Career Notes',
    time: 'Pinned',
    snippet: 'The history across IPF, freelancing, Ocean Tech Startup, Trilabs, and Finhub gives the portfolio range.',
  },
  {
    id: 'b5',
    category: 'LOW PRIORITY',
    title: 'Archive older experiments only after the flagship product stories are clear',
    sender: 'Cleanup Queue',
    time: 'Later',
    snippet: 'Projects like Tetris or smaller prototypes should support the narrative, not compete with the main portfolio work.',
  },
];

export const ROOM_ROWS: RoomRow[] = [
  {
    id: 'r1',
    source: 'Enterprise build',
    jobTitle: 'IPF OS platform',
    compensation: 'Flutter • TypeScript • Firebase • SSE',
    company: 'IPF Software',
    status: 'Live',
  },
  {
    id: 'r2',
    source: 'Mobile product',
    jobTitle: 'Bantu Soko',
    compensation: 'Flutter • Firebase • REST API',
    company: 'Play Store release',
    status: 'Live',
  },
  {
    id: 'r3',
    source: 'Finance product',
    jobTitle: 'Solomon Stockbroker',
    compensation: 'Flutter • Real-time market flows',
    company: 'Mobile investing app',
    status: 'Case Study',
  },
  {
    id: 'r4',
    source: 'Web product',
    jobTitle: 'Changisha crowdfunding',
    compensation: 'React • Firebase • Node.js',
    company: 'Fundraising platform',
    status: 'Active',
  },
  {
    id: 'r5',
    source: 'Experiment',
    jobTitle: 'Tetris mobile game',
    compensation: 'Flutter • Gameplay systems',
    company: 'Personal build',
    status: 'Archive',
  },
];

export const SEARCH_PROMPTS: SearchPrompt[] = [
  {
    id: 'p1',
    query: 'show me the best enterprise product Danford built',
    outputName: 'IPF OS (Enterprise Platform)',
    outputMeta: 'Cross-platform operations system with PMO, tasks, meals, and user management',
  },
  {
    id: 'p2',
    query: 'what mobile apps has Danford shipped publicly',
    outputName: 'Bantu Soko • Ocean • Tumafast',
    outputMeta: 'Public-facing mobile and commerce products across services, retail, and logistics',
  },
  {
    id: 'p3',
    query: 'summarize Danford roles in one line',
    outputName: 'Full Stack • DevOps • Mobile Engineer',
    outputMeta: 'Product-minded builder working across UI, APIs, deployment, and delivery',
  },
  {
    id: 'p4',
    query: 'find projects involving offline-first or community finance',
    outputName: 'Imbeju CRDB • Vikoba+',
    outputMeta: 'Tools designed for group finance workflows and practical field use',
  },
  {
    id: 'p5',
    query: 'pull out work history and shipped products for this portfolio',
    outputName: 'Career Timeline + Selected Work',
    outputMeta: 'IPF Software, freelancing, Ocean Tech Startup, Trilabs, Finhub, and more',
  },
];

export const PEOPLE_CONTACTS: PeopleContact[] = [
  {
    id: 'pp1',
    name: 'Danford Chriss',
    role: 'Full Stack, DevOps & Mobile Engineer',
    organization: 'danfordchris',
    avatarColor: '#ece6d2',
    bio: 'Builds web and mobile products with an emphasis on practical UX, scalable systems, and real delivery across enterprise and consumer software.',
    attributes: [
      { label: 'GITHUB', value: 'github.com/danfordChris' },
      { label: 'LINKEDIN', value: 'linkedin.com/in/danford-chriss-438364240' },
      { label: 'FOCUS', value: 'Products that ship' },
    ],
    pastInteractions: [
      { date: '2026', summary: 'Reshaped the portfolio to foreground shipped work, flagship systems, and public product links.' },
      { date: '2025', summary: 'Expanded the profile around enterprise, mobile, and delivery-oriented engineering.' },
    ],
    angle: 0,
  },
  {
    id: 'pp2',
    name: 'IPF Software',
    role: 'Current work context',
    organization: 'Enterprise platform delivery',
    avatarColor: '#ebdcb9',
    bio: 'The strongest portfolio proof point: a modular operations system spanning PMO, tasks, user management, and daily workflow tooling.',
    attributes: [
      { label: 'ROLE', value: 'Mobile Engineer' },
      { label: 'SINCE', value: '2025 - Present' },
      { label: 'FLAGSHIP', value: 'IPF OS' },
    ],
    pastInteractions: [
      { date: '2025', summary: 'Built cross-platform features and integrated backend workflows in production-oriented product work.' },
    ],
    angle: 51,
  },
  {
    id: 'pp3',
    name: 'Freelancing',
    role: 'Independent delivery track',
    organization: 'Client product work',
    avatarColor: '#d6cdb2',
    bio: 'A portfolio layer that shows adaptability: mobile builds, QA support, code reviews, and fast delivery for client needs.',
    attributes: [
      { label: 'ROLE', value: 'Mobile Engineer, QA' },
      { label: 'SINCE', value: '2023 - Present' },
      { label: 'STYLE', value: 'Hands-on shipping' },
    ],
    pastInteractions: [
      { date: '2024', summary: 'Maintained cross-platform mobile applications and improved performance across client-facing builds.' },
    ],
    angle: 102,
  },
  {
    id: 'pp4',
    name: 'Ocean Tech Startup',
    role: 'Flutter product chapter',
    organization: 'Commerce and mobile delivery',
    avatarColor: '#f2eae1',
    bio: 'Represents the product execution chapter around Flutter, Firebase integration, and e-commerce flow implementation.',
    attributes: [
      { label: 'ROLE', value: 'Flutter Developer' },
      { label: 'TIMELINE', value: '2023 - 2025' },
      { label: 'PRODUCT', value: 'Ocean app' },
    ],
    pastInteractions: [
      { date: '2023', summary: 'Shipped commerce-focused mobile work and improved application performance and user experience.' },
    ],
    angle: 153,
  },
  {
    id: 'pp5',
    name: 'Trilabs Limited',
    role: 'Backend and DevOps chapter',
    organization: 'Transport booking systems',
    avatarColor: '#dfd8bf',
    bio: 'Useful proof that the portfolio is not only UI work: APIs, deployment, payments, and operational backend thinking are part of the stack.',
    attributes: [
      { label: 'ROLE', value: 'Backend & DevOps' },
      { label: 'TIMELINE', value: '2022 - 2023' },
      { label: 'STRENGTH', value: 'Delivery pipelines' },
    ],
    pastInteractions: [
      { date: '2022', summary: 'Worked on transport booking APIs, payment integration, and continuous delivery practices.' },
    ],
    angle: 204,
  },
  {
    id: 'pp6',
    name: 'Finhub Community',
    role: 'Design and web chapter',
    organization: 'Community and client support',
    avatarColor: '#eae5d4',
    bio: 'Adds web design collaboration and community-driven delivery experience to the portfolio narrative.',
    attributes: [
      { label: 'ROLE', value: 'Web Designer' },
      { label: 'TIMELINE', value: '2022 - 2024' },
      { label: 'MODE', value: 'Collaborative' },
    ],
    pastInteractions: [
      { date: '2024', summary: 'Built websites and design-heavy client work in collaboration with organizations and startups.' },
    ],
    angle: 255,
  },
  {
    id: 'pp7',
    name: 'Public Profiles',
    role: 'Where the work continues',
    organization: 'GitHub • LinkedIn • Socials',
    avatarColor: '#ebd7c0',
    bio: 'The public layer of the portfolio: code presence, professional profile, product links, and a visible builder identity across the web.',
    attributes: [
      { label: 'X', value: 'x.com/Co24669' },
      { label: 'INSTAGRAM', value: 'instagram.com/royz_chriss' },
      { label: 'PORTFOLIO', value: 'danfordchris' },
    ],
    pastInteractions: [
      { date: 'Now', summary: 'Used as the final trust layer once visitors want to validate history, work, and identity.' },
    ],
    angle: 306,
  },
];

export const DRAWERS_DATA: DrawerDetail[] = [
  {
    id: 'dr1',
    label: 'Flagship',
    count: 2,
    color: '#cc4539',
    icon: 'Star',
    slips: [
      { id: 'sl1_1', title: 'IPF OS product brief', from: 'Selected Work', date: 'Pinned', snippet: 'Enterprise operations platform with mobile and web coverage.' },
      { id: 'sl1_2', title: 'Case study direction', from: 'Portfolio Desk', date: 'Pinned', snippet: 'Lead with system scope, architecture, and product screenshots.' },
    ],
  },
  {
    id: 'dr2',
    label: 'Timeline',
    count: 3,
    color: '#386dbd',
    icon: 'Calendar',
    slips: [
      { id: 'sl2_1', title: 'IPF Software', from: 'Career History', date: '2025 - Present', snippet: 'Mobile Engineer working on cross-platform production systems.' },
      { id: 'sl2_2', title: 'Freelancing', from: 'Career History', date: '2023 - Present', snippet: 'Client delivery across mobile work, QA, and performance cleanup.' },
      { id: 'sl2_3', title: 'Trilabs Limited', from: 'Career History', date: '2022 - 2023', snippet: 'Backend and DevOps work around booking, payments, and APIs.' },
    ],
  },
  {
    id: 'dr3',
    label: 'Web Builds',
    count: 4,
    color: '#378b60',
    icon: 'FileText',
    slips: [
      { id: 'sl3_1', title: 'Changisha App', from: 'Project Index', date: 'Web', snippet: 'Crowdfunding product focused on campaign creation and contribution flow.' },
      { id: 'sl3_2', title: 'Code Challenge App', from: 'Project Index', date: 'Web', snippet: 'Task planning interface inspired by Trello-like organization.' },
      { id: 'sl3_3', title: 'Nasafiri', from: 'Project Index', date: 'Web', snippet: 'Transport booking system designed to reduce booking friction.' },
      { id: 'sl3_4', title: 'Cypherz', from: 'Project Index', date: 'Web', snippet: 'Agriculture platform linking buyers and sellers directly.' },
    ],
  },
  {
    id: 'dr4',
    label: 'Mobile',
    count: 4,
    color: '#e2ad3c',
    icon: 'CreditCard',
    slips: [
      { id: 'sl4_1', title: 'Bantu Soko', from: 'Published Product', date: 'Android', snippet: 'Aggregated services and marketplace access in one mobile app.' },
      { id: 'sl4_2', title: 'MealGro', from: 'Published Product', date: 'Mobile', snippet: 'Meal planning, shopping lists, and low-waste UX.' },
      { id: 'sl4_3', title: 'Tumafast', from: 'Published Product', date: 'Mobile', snippet: 'Delivery logistics product for local package movement.' },
      { id: 'sl4_4', title: 'Vikoba+', from: 'Project Index', date: 'Mobile', snippet: 'Money management support for small-scale groups.' },
    ],
  },
  {
    id: 'dr5',
    label: 'Finance',
    count: 2,
    color: '#8b5e3c',
    icon: 'Plane',
    slips: [
      { id: 'sl5_1', title: 'Solomon Stockbroker', from: 'Project Index', date: 'Fintech', snippet: 'Mobile investing experience with portfolio tracking and market data.' },
      { id: 'sl5_2', title: 'Imbeju CRDB', from: 'Project Index', date: 'Offline-first', snippet: 'Community finance tooling for VIKOBA meeting workflows.' },
    ],
  },
  {
    id: 'dr6',
    label: 'Experiments',
    count: 2,
    color: '#c05621',
    icon: 'Package',
    slips: [
      { id: 'sl6_1', title: 'Tetris Game', from: 'Personal Build', date: 'Game', snippet: 'A focused mobile game experiment around control feel and replayability.' },
      { id: 'sl6_2', title: 'Stock Management', from: 'Product Lab', date: 'Prototype', snippet: 'Inventory and notification ideas for operational product management.' },
    ],
  },
  {
    id: 'dr7',
    label: 'Profiles',
    count: 3,
    color: '#6b7280',
    icon: 'Bell',
    slips: [
      { id: 'sl7_1', title: 'GitHub', from: 'Public Profile', date: 'Live', snippet: 'github.com/danfordChris' },
      { id: 'sl7_2', title: 'LinkedIn', from: 'Public Profile', date: 'Live', snippet: 'linkedin.com/in/danford-chriss-438364240' },
      { id: 'sl7_3', title: 'X + Instagram', from: 'Public Profile', date: 'Live', snippet: 'x.com/Co24669 and instagram.com/royz_chriss' },
    ],
  },
  {
    id: 'dr8',
    label: 'Stack',
    count: 3,
    color: '#8b5cf6',
    icon: 'BookOpen',
    slips: [
      { id: 'sl8_1', title: 'Mobile', from: 'Core Skill', date: 'Flutter', snippet: 'Cross-platform feature delivery and real product shipping.' },
      { id: 'sl8_2', title: 'Web', from: 'Core Skill', date: 'React', snippet: 'Interfaces, dashboards, and product-facing web experiences.' },
      { id: 'sl8_3', title: 'Systems', from: 'Core Skill', date: 'DevOps + APIs', snippet: 'Backend integration, deployment thinking, and operational workflows.' },
    ],
  },
  {
    id: 'dr9',
    label: 'Now',
    count: 2,
    color: '#ec4899',
    icon: 'Tag',
    slips: [
      { id: 'sl9_1', title: 'Sharpen portfolio signal', from: 'Current Focus', date: 'Now', snippet: 'Make flagship systems and published products obvious in the first minute.' },
      { id: 'sl9_2', title: 'Keep shipping', from: 'Current Focus', date: 'Now', snippet: 'Continue building practical products that combine strong UX with reliable engineering.' },
    ],
  },
];
