/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { HeroSnippet, BriefTask, RoomRow, PeopleContact, DrawerDetail, SearchPrompt } from './types';

// Let's create 22 visually diverse, scattered paper snippet cards for Scene 1
export const HERO_SNIPPETS: HeroSnippet[] = [
  {
    id: 's1',
    type: 'order',
    title: 'ORDER SUMMARY #5821',
    meta: 'Confirmed • 2 items • $124.50',
    body: 'Mugs, Coffee Grinder • Standard Shipping • Ship to Chelsea, NY',
    color: '#fffbf0', // cream post-it
    badge: 'SHIPPED',
    left: '8%',
    top: '12%',
    width: '180px',
    rotation: -12,
    delay: 0.1,
  },
  {
    id: 's2',
    type: 'employment',
    title: 'OFFER LETTER - ENG',
    meta: 'Airtable Inc. • Urgent response',
    body: 'Base Compensation: $185,000/yr • RSUs: 15,000 units • Remote',
    color: '#fcfcfc', // clean white bond
    stamp: 'ACCEPTED',
    stampColor: '#378b60',
    left: '25%',
    top: '8%',
    width: '210px',
    rotation: 5,
    delay: 0.2,
  },
  {
    id: 's3',
    type: 'alert',
    title: 'SECURITY ALERT: SIGN-IN',
    meta: 'Google Account • Chrome on Mac',
    body: 'New login detected near Berlin, Germany. Was this you?',
    color: '#fff3f3', // pale rose
    badge: 'SECURITY',
    left: '75%',
    top: '10%',
    width: '190px',
    rotation: -8,
    delay: 0.3,
  },
  {
    id: 's4',
    type: 'offer',
    title: 'CLAIM OFFER - $250 BACK',
    meta: 'Chase Business Card',
    body: 'Spend $1,000 in your first 3 months to receive cashback.',
    color: '#f0f6ff', // light blue index card
    stamp: 'PROMOTION',
    stampColor: '#386dbd',
    left: '84%',
    top: '16%',
    width: '180px',
    rotation: 14,
    delay: 0.4,
  },
  {
    id: 's5',
    type: 'delivery',
    title: 'FedEx DELIVERED',
    meta: 'Tracking: #958210482',
    body: 'Left on porch • Signature not required • Heavy box',
    color: '#faf6f0',
    badge: 'DELIVERY',
    left: '5%',
    top: '38%',
    width: '160px',
    rotation: 8,
    delay: 0.15,
  },
  {
    id: 's6',
    type: 'flight',
    title: 'FLIGHT LX402 TO ZURICH',
    meta: 'Swiss Air • Dep: 14:20 ORD',
    body: 'Terminal 5 • Gate M12 • Seat 22A (Window) • Boarding 13:40',
    color: '#eefcf5', // light green ticket
    badge: 'FLIGHT',
    left: '12%',
    top: '65%',
    width: '200px',
    rotation: -6,
    delay: 0.25,
  },
  {
    id: 's7',
    type: 'promo',
    title: 'Figma Pro subscription',
    meta: 'Billing Invoice #8402',
    body: 'Amount Paid: $45.00 via Amex *2004 • Thank you!',
    color: '#faf9f5',
    stamp: 'PAID',
    stampColor: '#cc4539',
    left: '24%',
    top: '82%',
    width: '170px',
    rotation: -10,
    delay: 0.35,
  },
  {
    id: 's8',
    type: 'job_confirmation',
    title: 'RE: Senior React Role',
    meta: 'Vercel Recruiting Team',
    body: 'We loved your technical conversation. Next step is a chat with Lee Robinson.',
    color: '#ffffff',
    badge: 'RECRUITING',
    left: '42%',
    top: '84%',
    width: '220px',
    rotation: 4,
    delay: 0.45,
  },
  {
    id: 's9',
    type: 'coupon',
    title: 'WEEKEND MEMO: COFFEE',
    meta: 'Blue Bottle • 20% OFF',
    body: 'Use code BREW-SUNDAY on whole beans order this weekend.',
    color: '#fffdf5',
    left: '72%',
    top: '80%',
    width: '160px',
    rotation: -15,
    delay: 0.5,
  },
  {
    id: 's10',
    type: 'delivery_tag',
    title: 'DHL NOTICE',
    meta: 'Delivered at mailbox',
    color: '#fffcf0',
    badge: 'DHL EXPRESS',
    left: '88%',
    top: '72%',
    width: '150px',
    rotation: 12,
    delay: 0.55,
  },
  {
    id: 's11',
    type: 'mugs_note',
    title: 'CRAFT COFFEE ORDER',
    meta: '$18.00 • Espresso Roast',
    color: '#faf9f5',
    left: '86%',
    top: '42%',
    width: '140px',
    rotation: -7,
    delay: 0.6,
  },
  {
    id: 's12',
    type: 'house_icon_note',
    title: 'APARTMENT TOUR',
    meta: 'Sunday 12:00 PM',
    body: '64 Greene St #4B • Buzzer: 042 • Host: Sarah Jones',
    color: '#fffff8',
    stamp: 'MARKED',
    stampColor: '#386dbd',
    left: '69%',
    top: '48%',
    width: '180px',
    rotation: 8,
    delay: 0.65,
  },
  // Additional scatter cards to hit 22 pieces
  {
    id: 's13',
    type: 'note',
    title: 'Draft: Pitch Deck v2',
    meta: 'Google Slide Share',
    color: '#fffdf0',
    left: '45%',
    top: '4%',
    width: '140px',
    rotation: -3,
    delay: 0.7,
  },
  {
    id: 's14',
    type: 'note',
    title: 'Receipt: Uber Eats',
    meta: 'Total $24.80 • Dinner',
    color: '#ffffff',
    badge: 'EXPENSE',
    left: '58%',
    top: '6%',
    width: '130px',
    rotation: 11,
    delay: 0.75,
  },
  {
    id: 's15',
    type: 'alert',
    title: 'Calendar: 1:1 w/ CEO',
    meta: 'Tomorrow • 10:00 AM',
    color: '#fcfcf0',
    left: '2%',
    top: '25%',
    width: '140px',
    rotation: -18,
    delay: 0.8,
  },
  {
    id: 's16',
    type: 'logo',
    title: 'Vector V3 Export',
    meta: 'attachment.svg',
    color: '#eef8ff',
    left: '26%',
    top: '28%',
    width: '130px',
    rotation: 6,
    delay: 0.85,
  },
  {
    id: 's17',
    type: 'note',
    title: 'SaaS Bill: Vercel',
    meta: 'Charged card: $20.00',
    color: '#fcfcfc',
    stamp: 'PAID',
    stampColor: '#378b60',
    left: '79%',
    top: '32%',
    width: '120px',
    rotation: -9,
    delay: 0.9,
  },
  {
    id: 's18',
    type: 'note',
    title: 'Y Combinator W27',
    meta: 'Submission successful',
    body: 'Receipt of early application #4912.',
    color: '#fffbf4',
    left: '62%',
    top: '19%',
    width: '170px',
    rotation: 3,
    delay: 0.95,
  },
  {
    id: 's19',
    type: 'note',
    title: 'Stripe Payout',
    meta: '+$4,250.00 • Transfer',
    color: '#f4fbf0',
    left: '5%',
    top: '80%',
    width: '140px',
    rotation: 9,
    delay: 1.0,
  },
  {
    id: 's20',
    type: 'note',
    title: 'Gym Membership',
    meta: 'Active subscription',
    color: '#ffffff',
    left: '18%',
    top: '50%',
    width: '130px',
    rotation: -16,
    delay: 1.05,
  },
  {
    id: 's21',
    type: 'note',
    title: 'Newsletter: TLDR Tech',
    meta: 'Apple AI chips & chips',
    color: '#fffff8',
    left: '80%',
    top: '59%',
    width: '150px',
    rotation: 5,
    delay: 1.1,
  },
  {
    id: 's22',
    type: 'note',
    title: 'Taxes: W2 Form',
    meta: 'IRS • Ready to import',
    color: '#fcf8ee',
    stamp: 'TAX-DOC',
    stampColor: '#cc4539',
    left: '58%',
    top: '85%',
    width: '170px',
    rotation: -4,
    delay: 1.15,
  },
];

// Tasks for notebook in Scene 2
export const BRIEF_TASKS: BriefTask[] = [
  {
    id: 'b1',
    category: 'MUST SEE',
    title: 'Setup background checks and employee onboarding documents',
    sender: 'Kelly O’Connor (HR Partner)',
    time: '14 minutes ago',
    tags: ['Onboarding', 'Action Required'],
    snippet: 'Hey! We have 3 new hires starting on Monday. Can you confirm legal signing and setup their workplace emails?',
    actionRequired: true,
  },
  {
    id: 'b2',
    category: 'MUST SEE',
    title: 'Job Offer Negotiations & Final Signatures',
    sender: 'Derrick Smith (VP Engineering)',
    time: '1 hour ago',
    snippet: 'Hey mate, Kiara agreed to the compensation adjustment ($195k base). Sending standard contract payload.',
    attachment: { name: 'Logo V3. SVG', size: '256 KB' },
  },
  {
    id: 'b3',
    category: 'FYI',
    title: 'Added to room "Job Application" tracker list',
    sender: 'System Bot',
    time: '2 hours ago',
    tags: ['Automated Ledger'],
    snippet: 'Candidate Kiara Easwaran was auto-merged from LinkedIn into applicant pool dashboard.',
  },
  {
    id: 'b4',
    category: 'FYI',
    title: 'Investor Pitch deck feedback session',
    sender: 'Scott Adams (Founders Circle)',
    time: '3 hours ago',
    snippet: 'Slide 12 (Capital efficiency run-rate) looks amazing. Safe to proceed with the series seed closure.',
  },
  {
    id: 'b5',
    category: 'LOW PRIORITY',
    title: 'Weekend coffee meet requests & Slack notifications',
    sender: 'Promotions Digest',
    time: '1 day ago',
    snippet: 'Special discount alert from Blue Bottle, and 4 unread messages in #general channel lounge.',
  },
];

// Database Rows for Room in Scene 3
export const ROOM_ROWS: RoomRow[] = [
  {
    id: 'r1',
    source: 'LinkedIn Import',
    jobTitle: 'VP of Product Engineering',
    compensation: '$210,000 + 1.2%',
    company: 'Linear App Corp',
    status: 'Interview',
  },
  {
    id: 'r2',
    source: 'Direct email referral',
    jobTitle: 'Lead Design Engineer',
    compensation: '$195,000 + 0.8%',
    company: 'Feather Systems',
    status: 'Accepted',
  },
  {
    id: 'r3',
    source: 'Hired Platform match',
    jobTitle: 'Senior Systems Architect',
    compensation: '$240,000 + 0.5%',
    company: 'Supabase Inc',
    status: 'Interview',
  },
  {
    id: 'r4',
    source: 'Website Submission',
    jobTitle: 'Junior Frontend Developer',
    compensation: '$110,000 + 0.1%',
    company: 'Vercel Labs',
    status: 'Applied',
  },
  {
    id: 'r5',
    source: 'Angellist Talent',
    jobTitle: 'Data Infra Lead',
    compensation: '$180,000 + 0.7%',
    company: 'Skiff Privacy',
    status: 'Rejected',
  },
];

// Prompts & Outputs for Scene 4 Search Engine
export const SEARCH_PROMPTS: SearchPrompt[] = [
  {
    id: 'p1',
    query: 'find a birthday cake photo from Kathy Liu',
    outputName: 'kathy_birthday_cake_high_res.png',
    outputMeta: 'Kathy Liu • June 12 • Attachment in thread: "Happy 30th!"',
  },
  {
    id: 'p2',
    query: 'send each customer a personal email about the new product',
    outputName: 'Emailed 42 Enterprise Accounts',
    outputMeta: 'Drafted and queued safely • Template matching CRM guidelines',
  },
  {
    id: 'p3',
    query: 'add office address to Jason meeting',
    outputName: 'Cal Event: Jason 1:1',
    outputMeta: 'Added: 450 Broadway, Suite 500, New York • Nudged calendar',
  },
  {
    id: 'p4',
    query: 'send lawyer incorporation documents',
    outputName: 'Delivered: Delaware_Articles_Inc_Final.pdf',
    outputMeta: 'Sent to legal-intake@wilsonsonsini.com • Logged on Drive',
  },
  {
    id: 'p5',
    query: 'mark promotions/newsletters as read',
    outputName: 'Uncluttered Inbox: 184 Items Archived',
    outputMeta: 'Muted promos safely • Keeps your daily view neat and pristine',
  },
];

// People connections for Scene 5
export const PEOPLE_CONTACTS: PeopleContact[] = [
  {
    id: 'pp1',
    name: 'Derrick Smith',
    role: 'VP of Engineering',
    organization: 'Danford Systems',
    avatarColor: '#ece6d2',
    bio: 'Former Tech Lead at Linear and Stripe engineering. Expert in web performance, databases, custom compilers, and modern paper computer models.',
    attributes: [
      { label: 'EMAIL', value: 'derrick@danfordchris.computer' },
      { label: 'LOCATION', value: 'San Francisco, CA' },
      { label: 'RELATIONSHIP', value: 'Team Member' },
    ],
    pastInteractions: [
      { date: 'Jun 22, 2026', summary: 'Sent technical specs for workspace drawer slips ejection.' },
      { date: 'Jun 18, 2026', summary: 'Agreed to compensations adjustment of Kiara to $195k.' },
    ],
    angle: 0,
  },
  {
    id: 'pp2',
    name: 'Emily Johanson',
    role: 'Product Designer',
    organization: 'Remix Lab',
    avatarColor: '#ebdcb9',
    bio: 'Passionate about retro and tactile user experiences, typography, letter-spacing, and stationary craftmanship.',
    attributes: [
      { label: 'EMAIL', value: 'emily@remix.design' },
      { label: 'PORTFOLIO', value: 'emily.remix.design' },
      { label: 'SOURCE', value: 'Figma referral' },
    ],
    pastInteractions: [
      { date: 'May 10, 2026', summary: 'Designed stamp-wiggle animation prototypes for our notebook layout.' },
    ],
    angle: 51,
  },
  {
    id: 'pp3',
    name: 'Scott Adams',
    role: 'General Partner',
    organization: 'Founders Circle',
    avatarColor: '#d6cdb2',
    bio: 'Early supporter of modern user-focused systems. Believer in full-viewport staged web aesthetics instead of standard SaaS grids.',
    attributes: [
      { label: 'INVESTOR', value: 'Pre-Seed Lead ($1.5M)' },
      { label: 'CONTACT', value: 'scott@founderscircle.vc' },
      { label: 'TERM SHEET', value: 'Executed 2025' },
    ],
    pastInteractions: [
      { date: 'Jun 20, 2026', summary: 'Reviewed slide deck 12 capital efficiency run-rate.' },
    ],
    angle: 102,
  },
  {
    id: 'pp4',
    name: 'Kiara Easwaran',
    role: 'Senior React Developer',
    organization: 'Applicant',
    avatarColor: '#f2eae1',
    bio: 'Candidate imported directly from LinkedIn. Specializes in custom virtual scroll systems, micro-animations, and type-safe frontends.',
    attributes: [
      { label: 'STATUS', value: 'Offer Sent • Accepted' },
      { label: 'OFFER BASE', value: '$195,000/yr' },
      { label: 'SOURCE', value: 'LinkedIn Import' },
    ],
    pastInteractions: [
      { date: 'Jun 21, 2026', summary: 'Added candidate record to our Job Application room.' },
    ],
    angle: 153,
  },
  {
    id: 'pp5',
    name: 'José Martínez',
    role: 'Creative Director',
    organization: 'Stamp Guild',
    avatarColor: '#dfd8bf',
    bio: 'Specialist in tangible brand elements, ink pigments, physical post-it notes, and letterpress designs.',
    attributes: [
      { label: 'SKILL', value: 'Letterpress Branding' },
      { label: 'COFFEE INTAKE', value: 'Pour-over expert' },
    ],
    pastInteractions: [
      { date: 'Apr 02, 2026', summary: 'Mailed custom ink pigment recipes for the green validation stamp.' },
    ],
    angle: 204,
  },
  {
    id: 'pp6',
    name: 'Cheng Tan',
    role: 'Data Engineer',
    organization: 'Pinecone Systems',
    avatarColor: '#eae5d4',
    bio: 'Expert database architect, vector indices optimizer, and high-frequency search query pipelining engineer.',
    attributes: [
      { label: 'LOCATION', value: 'New York, NYC' },
      { label: 'LANGUAGES', value: 'Rust, TypeScript' },
    ],
    pastInteractions: [
      { date: 'Jun 12, 2026', summary: 'Discussed vertical receipt machine design speed to improve latency.' },
    ],
    angle: 255,
  },
  {
    id: 'pp7',
    name: 'Daniel Weiss',
    role: 'Founding Engineer',
    organization: 'Danford Systems',
    avatarColor: '#ebd7c0',
    bio: 'Author of the custom virtual scroll snap mechanics. Focused on elegant desktop wheel interceptions and zero HMR flicker solutions.',
    attributes: [
      { label: 'CODEBASE', value: 'https://github.com/danfordchris' },
      { label: 'INTERESTS', value: 'Old print design books' },
    ],
    pastInteractions: [
      { date: 'Jun 23, 2026', summary: 'Updated index.css with Google fonts variables: Instrument & IBM.' },
    ],
    angle: 306,
  },
];

// Detail Content of Drawers (Scene 7)
export const DRAWERS_DATA: DrawerDetail[] = [
  {
    id: 'dr1',
    label: 'Important',
    count: 2,
    color: '#cc4539', // dynamic ink / stamp tag highlight
    icon: 'Star',
    slips: [
      { id: 'sl1_1', title: 'Workplace Offer Sign-Off Required', from: 'Kelly O’Connor', date: 'Just now', snippet: 'Urgent onboarding agreement for Kiara starting next Monday.' },
      { id: 'sl1_2', title: 'Delaware Corporation Articles APPROVED', from: 'SEC Filing Service', date: '2 hours ago', snippet: 'Standard W2 setup is green, filed with state registrars.' },
    ],
  },
  {
    id: 'dr2',
    label: 'Meeting',
    count: 3,
    color: '#386dbd',
    icon: 'Calendar',
    slips: [
      { id: 'sl2_1', title: '1:1 Progress Check-in', from: 'CEO Room', date: 'Tomorrow 10:00 AM', snippet: 'Agenda: review latest pitch deck slides and vector logos.' },
      { id: 'sl2_2', title: 'Office Space Virtual Tour', from: 'Sarah Jones', date: 'Jun 25, 12:00 PM', snippet: 'Touring 64 Greene St. Buzz for access.' },
      { id: 'sl2_3', title: 'Recruiting Debrief Vercel Roles', from: 'HR Recruiting', date: 'Jun 26, 03:00 PM', snippet: 'Evaluating developer candidates and compensation plans.' },
    ],
  },
  {
    id: 'dr3',
    label: 'Shared File',
    count: 4,
    color: '#378b60',
    icon: 'FileText',
    slips: [
      { id: 'sl3_1', title: 'Pitch_Deck_V2_Draft.pdf', from: 'Scott Adams', date: '1 day ago', snippet: 'Investor deck version with updated seed capitalization info.' },
      { id: 'sl3_2', title: 'Corporate_Logo_Monochrome.svg', from: 'Emily Johanson', date: '3 days ago', snippet: 'Clean vector asset for the branding header bar.' },
      { id: 'sl3_3', title: 'Offer_Letter_Draft.docx', from: 'Legal Team', date: '5 days ago', snippet: 'Employment legal clause boilerplate.' },
      { id: 'sl3_4', title: 'IRS_Form_W9_Corporate.pdf', from: 'Accounting Ledger', date: '1 week ago', snippet: 'Filled tax documentation.' },
    ],
  },
  {
    id: 'dr4',
    label: 'Spending',
    count: 2,
    color: '#e2ad3c',
    icon: 'CreditCard',
    slips: [
      { id: 'sl4_1', title: 'Figma Pro subscription renewal', from: 'Figma Billing', date: 'Yesterday', amount: '$45.00', snippet: 'Recurring charge successfully processed via Amex.' },
      { id: 'sl4_2', title: 'Catering: Lunch for Team', from: 'Uber Eats', date: '3 days ago', amount: '$218.40', snippet: 'Organic salad bowls and coffee carafes.' },
    ],
  },
  {
    id: 'dr5',
    label: 'Booking',
    count: 1,
    color: '#8b5e3c',
    icon: 'Plane',
    slips: [
      { id: 'sl5_1', title: 'Boarding Pass Flight LX402', from: 'Swiss Airlines', date: 'Jun 28', snippet: 'Departure Chicago Chicago ORD at 14:20, Boarding at 13:40.' },
    ],
  },
  {
    id: 'dr6',
    label: 'Package',
    count: 2,
    color: '#c05621',
    icon: 'Package',
    slips: [
      { id: 'sl6_1', title: 'Standard Shipment Left on Porch', from: 'FedEx SmartPost', date: '2 days ago', snippet: '1x Heavy Mug Box and coffee filters. Sealed package.' },
      { id: 'sl6_2', title: 'In-transit: Custom Wax Seal Stamp kit', from: 'DHL Express', date: 'Estimated Friday', snippet: 'Shipped from Zurich, Switzerland.' },
    ],
  },
  {
    id: 'dr7',
    label: 'Notification',
    count: 1,
    color: '#2c3e50',
    icon: 'Bell',
    slips: [
      { id: 'sl7_1', title: 'New login detected from Berlin, Germany', from: 'Google Security', date: 'Jun 21', snippet: 'Chrome on Mac OS. If this was not you, lock credentials.' },
    ],
  },
  {
    id: 'dr8',
    label: 'Newsletter',
    count: 3,
    color: '#7f8c8d',
    icon: 'BookOpen',
    slips: [
      { id: 'sl8_1', title: 'The Future of Tactile Operating Models', from: 'TLDR Tech Newsletter', date: '2 days ago', snippet: 'Analyzing why microcomputers are embracing mechanical paper aesthetics.' },
      { id: 'sl8_2', title: 'Weekly design digest #452', from: 'Figma Design', date: '5 days ago', snippet: 'Interactive variables, custom letterpress, and layout grids.' },
      { id: 'sl8_3', title: 'Handmade stationery curation catalog', from: 'The Stamp Guild', date: '1 week ago', snippet: 'Imported cotton papers, customized copper tags.' },
    ],
  },
  {
    id: 'dr9',
    label: 'Promotion',
    count: 1,
    color: '#9b59b6',
    icon: 'Tag',
    slips: [
      { id: 'sl9_1', title: 'Claim offering: $250 credit promo', from: 'Chase Card Service', date: '3 weeks ago', snippet: 'Sign up for Ink Business and execute minimal monthly card spends.' },
    ],
  },
];
